export const languages = {
  fr: {
    home: {
      titre: "Votre activité du jour",
      hero1: "Votre musique",
      hero2: "décryptée",
      herop1: "Analysez vos habitudes d'écoute avec une précision chirurgicale.",
      herop2: "Découvrez ce qui fait vibrer votre algorithme.",
      btn1: "Analyser mon profil",
      learnMore: "En savoir plus",
      stats1: "Streams analysés",
      stats2: "Utilisateurs",
      stats3: "Musiques",
      stats4: "Albums",
      stats5: "Artistes",
      techtitre: "Le Projet MyStats",
    },
    account: {
      successToast: "Compte mis à jour avec succès !",
      confirmDelete: "Pour confirmer la suppression de votre compte et de toutes vos statistiques, tapez 'SUPPRIMER' ci-dessous :",
      deleteValidation: "SUPPRIMER",
      successDeleteToast: "Votre compte a été supprimé avec succès.",
      errorDeleteMessage: "Erreur lors de la suppression.",
      confirmClear: "Pour confirmer le nettoyage de vos données et de toutes vos statistiques, tapez 'CONFIRMER' ci-dessous :",
      clearValidation: "CONFIRMER",
      successToastClear: "Vos données ont été supprimées avec succès.",
      lefttitle: 'Profil',
      leftsubtitle: 'Gérez vos informations.',
      titleDisplayname: "Nom d'affichage",
      errorName1: "Le nom d'affichage doit faire au moins 3 caractères.",
      errorName2: "Le nom d'affichage doit faire maximum 20 caractères.",
      placeholderName: "Ton pseudo...",
      emailtitle: "Adresse email",
      passwordtitle: "Nouveau mot de passe (optionnel)",
      errorPw1: "Le mot de passe doit faire au moins 8 caractères.",
      errorPw2: "Le mot de passe doit faire maximum 128 caractères.",
      errorPw3: "Les mots de passe ne correspondent pas.",
      placeholderPw: "Laisser vide pour ne pas changer...",
      confirmpwtitle: "Confirmer le nouveau mot de passe",
      placeholderpwc: "Confirme ton mot de passe...",
      saving: "Enregistrement...",
      save: "Enregistrer les modifications",
      righttitle: 'Services',
      rightsubtitle: 'Liaison de comptes tiers.',
      synchronized: "Votre compte est synchronisé",
      notsynchronized: "Non synchronisé",
      linkSpotify: "Lier mon compte Spotify",
      littleNote: "La liaison Spotify permet à MyStats de récupérer vos écoutes.",
      cleardata: "Nettoyer mes données",
      deleteaccount: "Supprimer mon compte MyStats",
      littleNote2: "Ces actions sont irréversibles. Toutes vos statistiques et données de profil seront définitivement effacées."
    },
    auth: {
      spotifyError1: "Connexion Spotify annulée.",
      spotifyError2: "Impossible de récupérer l'accès Spotify.",
      spotifyError3: "Échec de la récupération du profil Spotify.",
      spotifyError4: "Paramètres d'authentification manquants.",
      spotifyErrorTemplate: "Erreur Spotify",
      errorOccured: "Une erreur est survenue lors de la connexion.",
      welcome: "Bienvenue !",
      errorPw1: "Le mot de passe doit faire au moins 8 caractères.",
      errorPw2: "Une erreur est survenue. Impossible de créer le compte.",
      errorPw3: "Les mots de passe ne correspondent pas.",
      connecttitle: 'Connexion',
      comeback: 'Bon retour sur MyStats.',
      connectwithspotify: "Continuer avec Spotify",
      ou: "Ou",
      connecting: "Connexion...",
      connect: "Se connecter",
      righttitle: 'S\'inscrire',
      rightsubtitle: 'Nouveau ici ? Bienvenue.',
      username: "Nom d'utilisateur",
      emailtitle: "Adresse email",
      templateemail: "votre@email.com",
      pw: "Mot de passe",
      confirm: "Confirmation",
      creating: "Création...",
      create: "Créer mon compte",
      littleNote: "En créant un compte, vous acceptez nos conditions d'utilisation et notre politique de confidentialité."
    },
    api: {
      errorTemplate: "Erreur sur",
      error1: 'Une erreur inattendue est survenue',
      redirect: "Session expirée, redirection...",
      errorConnecting: "Connexion au serveur impossible.",
    },
    error: {
      title1: "Accès Privé",
      message1: "Ce profil est privé. L'utilisateur a choisi de ne pas partager ses statistiques.",
      title2: "Introuvable",
      message2: "La ressource ou l'utilisateur que vous cherchez n'existe pas.",
      titleDefault: "Oups !",
      messageDefault: "Une erreur inattendue est survenue.",
      retry: "Réessayer",
      backhome: "Retour à l'accueil",
      backpage: "Page précédente"
    }
  },
  en: {
    home: {
      titre: "Daily activity",
      hero1: "Your music",
      hero2: "decrypted",
      herop1: "Analyze your listening habits with surgical precision.",
      herop2: "Discover what makes your algorithm tick.",
      btn1: "Analyze my profile",
      learnMore: "Learn more",
      stats1: "Streams analyzed",
      stats2: "Users",
      stats3: "Musics",
      stats4: "Albums",
      stats5: "Artists",
      techtitre: "The MyStats Project",
    },
    account: {
      successToast: "Account successfully updated !",
      confirmDelete: "To confirm the deletion of your account and all your statistics, type 'DELETE' below :",
      deleteValidation: "DELETE",
      successDeleteToast: "Your account has been successfully deleted.",
      errorDeleteMessage: "Error during deletion.",
      confirmClear: "To confirm the clearing of your data and all your statistics, type 'CONFIRM' below :",
      clearValidation: "CONFIRM",
      successToastClear: "Your data has been successfully deleted.",
      lefttitle: 'Profile',
      leftsubtitle: 'Manage your information.',
      titleDisplayname: "Displayname",
      errorName1: "The display name must be at least 3 characters long.",
      errorName2: "The display name must be a maximum of 20 characters.",
      placeholderName: "Your nickname...",
      emailtitle: "Email address",
      passwordtitle: "New password (optional)",
      errorPw1: "The password must be at least 8 characters long.",
      errorPw2: "The password must be a maximum of 128 characters.",
      errorPw3: "The passwords do not match.",
      placeholderPw: "Leave it blank so as not to change...",
      confirmpwtitle: "Confirm the new password",
      placeholderpwc: "Confirm your password...",
      saving: "Saving...",
      save: "Save changes",
      righttitle: 'Services',
      rightsubtitle: 'Linking third-party accounts.',
      synchronized: "Your account is synchronized",
      notsynchronized: "Not synchronized",
      linkSpotify: "Link my Spotify account",
      littleNote: "The Spotify connection allows MyStats to retrieve your listening data.",
      cleardata: "Clean up my data",
      deleteaccount: "Delete my MyStats account",
      littleNote2: "These actions are irreversible. All your statistics and profile data will be permanently deleted."
    },
    auth: {
      spotifyError1: "Spotify connection canceled.",
      spotifyError2: "Unable to regain Spotify access.",
      spotifyError3: "Spotify profile recovery failed.",
      spotifyError4: "Missing authentication parameters.",
      spotifyErrorTemplate: "Spotify error",
      errorOccured: "An error occurred during the connection.",
      welcome: "Welcome !",
      errorPw1: "The password must be at least 8 characters long.",
      errorPw2: "An error has occurred. Unable to create the account.",
      errorPw3: "The passwords do not match.",
      connecttitle: 'Log in',
      comeback: 'Welcome back to MyStats.',
      connectwithspotify: "Continue with Spotify",
      ou: "Or",
      connecting: "Logging in...",
      connect: "Log in",
      righttitle: 'Register',
      rightsubtitle: 'New here? Welcome.',
      username: "Username",
      emailtitle: "Email address",
      templateemail: "your@email.com",
      pw: "Password",
      confirm: "Confirm",
      creating: "Creating...",
      create: "Create account",
      littleNote: "By creating an account, you agree to our terms of use and privacy policy."
    },
    api: {
      errorTemplate: "Error on",
      error1: 'An unexpected error has occurred.',
      redirect: "Session expired, redirection...",
      errorConnecting: "Unable to connect to server.",
    },
    error: {
      title1: "Private Access",
      message1: "This profile is private. The user has chosen not to share their statistics.",
      title2: "Not Found",
      message2: "The resource or user you are looking for does not exist.",
      titleDefault: "Oops!",
      messageDefault: "An unexpected error occurred.",
      retry: "Try Again",
      backhome: "Back to Home",
      backpage: "Previous Page"
    }
  }
}