const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";

export const API_ENDPOINTS = {
  REGISTER: `${API_BASE_URL}/auth/register`,
  LOGIN: `${API_BASE_URL}/auth/login`,
  LOGOUT:`${API_BASE_URL}/auth/logout`,
  ME: `${API_BASE_URL}/auth/me`,
  EDIT_INFOS: `${API_BASE_URL}/auth/update`,
  DELETE_ACCOUNT: `${API_BASE_URL}/auth/delete`,
  CLEAR_ACCOUNT: `${API_BASE_URL}/data/my/clear`,
  SPOTIFY_LOGIN: `${API_BASE_URL}/auth/spotify-login`,
  // UNLINK_SPOTIFY: `${API_BASE_URL}/auth/unlink-spotify`,
  HOME_DATA: `${API_BASE_URL}/data/overview`,
  HISTORY:`${API_BASE_URL}/data/my/history`,
  TRACKS:`${API_BASE_URL}/data/my/tracks`,
  TRACKS_METADATA:`${API_BASE_URL}/data/my/tracks/metadata`,
  ARTISTS:`${API_BASE_URL}/data/my/artists`,
  ARTISTS_METADATA:`${API_BASE_URL}/data/my/artists/metadata`,
  ALBUMS:`${API_BASE_URL}/data/my/albums`,
  ALBUMS_METADATA:`${API_BASE_URL}/data/my/albums/metadata`,
  UPLOAD_JSON:`${API_BASE_URL}/data/my/upload-json`,
  IMPORT_DATA:`${API_BASE_URL}/data/my/upload-json`,
  ALL_HISTORY:`${API_BASE_URL}/data/all/history`,
  ALL_TRACKS:`${API_BASE_URL}/data/all/tracks`,
  ALL_TRACKS_METADATA:`${API_BASE_URL}/data/all/tracks/metadata`,
  ALL_ARTISTS:`${API_BASE_URL}/data/all/artists`,
  ALL_ARTISTS_METADATA:`${API_BASE_URL}/data/all/artists/metadata`,
  ALL_ALBUMS:`${API_BASE_URL}/data/all/albums`,
  ALL_ALBUMS_METADATA:`${API_BASE_URL}/data/all/albums/metadata`,
  SPOTIFY_STATUS:`${API_BASE_URL}/spotify/status`,
  PROFILE_DATA: `${API_BASE_URL}/profile`,
  SIMPLE_PROFILE_DATA: `${API_BASE_URL}/profile/simple`,
  EDITABLE_PROFILE_DATA: `${API_BASE_URL}/edit-profile`,
  DASHBOARD_DATA: `${API_BASE_URL}/profile/dashboard`,
};

export const FRONT_ROUTES = {
  ACCUEIL: '/',
  AUTH: '/auth',
  MY_RANKINGS: '/my/',
  ALL_RANKINGS: '/all/',
  IMPORT: '/import',
  ACCOUNT: '/account',
  DASHBOARD: '/profile/dashboard',
  ABOUT: '/about',
  PROFILE: '/profile',
  PROFILE_EDIT: '/profile/edit',
  HELP: '/faq',
}